# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: self
    type: git
    name: "EDHEC Grading System/EDHEC - API"
    ref: develop
    trigger:
    - develop
  - repository: WEB
    type: git
    name: "EDHEC Grading System/EDHEC - WEB"
    ref: develop
    trigger:
    - develop

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- checkout: WEB

- script: |
    ls
  displayName: 'List files'
