version: "3.9"
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: authapi
      POSTGRES_PASSWORD: authapi
      POSTGRES_USER: authapi
    volumes:
       - pg_data:/var/lib/postgresql/database
    ports:
      - "5434:5432"
volumes:
  pg_data: